### ISSUE TITLE
Update to map specific configs issue?

### ISSUE THREAD

**Issue by alvinthechipmunk** [Lange/SOAP-TF2DM#23]
Ever since the update to the map specific configs, I've found that SOAP runs on every map that is played now. whether it's mge or just cp_gorge, the health regen is always there and it messes with the mge spawns. Using the older version where there's just soap.cfg fixes the issue.

Any idea what i'm doing wrong?

**Comment by Lange** [comment]
@slate17, can you look into this?

**Comment by slate17** [comment]
@Lange , will do.

**Comment by Lange** [comment]
Thanks @slate17 .

@alvinthechipmunk this issue should be fixed now.
