### ISSUE TITLE
Overheal issues

### ISSUE THREAD

**Issue by SpiritBob** [Lange/SOAP-TF2DM#29]
If I'm over-healed and i get healed by soap, my bonus health is gone, and for some reason soap breaks plugins that set your health to 5000 or 22200. Also there is no option to enable lockers (soap blocks them permanently)

Can you address to fixing the over-heal? That is my biggest problem. If I have bonus health, it shouldn't be removed after I get a "heal" from soap, because in reality that isn't a heal at all!

EDIT: It even applies to over-healing in general. Was just with a medic, you can't seem to over-heal anybody. The moment his health goes into an over-heal state, it shuts down to normal. The healing rate is also a bit buggy.

Thank you.

**Comment by Lange** [comment]
I unfortunately no longer maintain this plugin, but perhaps someone who is still active in the TF2 community will see this issue and offer up a pull request.

**Comment by Lange** [comment]
Addressed by #30. Thanks @mr64bit!

**Comment by SpiritBob** [comment]
Thank you @mr64bit.

**Comment by SpiritBob** [comment]
@mr64bit @Lange After testing a bit, healing someone with the medic still bugs after they get healed by soap (They lose their overheal). I'm using the soap_dmg_heal_ratio for healing.

**Comment by icewind1991** [comment]
Fixed with bc3ce5ec3822b3ed90e0e2e2e53f92d2c91b2384
