### ISSUE TITLE
Overheal issue still not fixed

### ISSUE THREAD

**Issue by SpiritBob** [Lange/SOAP-TF2DM#32]
Just letting this hang here, for anyone willing to fix it. Locker is working fine and so is everything else. Just need to make it so that kills do not remove any kind of over-heal.

Thanks again @mr64bit for adding a locker option! :)

**Comment by mr64bit** [comment]
Unfortunately I've not had time to fix this, but you're welcome to try it yourself. You'd probably have to do something similar to what I did (https://github.com/Lange/SOAP-TF2DM/commit/4b21303fa736c7095dd6fd2e8fe2759292c3b807#diff-93c629c2fc9a99d985885a9d5e4aa86dR682) here: https://github.com/Lange/SOAP-TF2DM/blob/master/addons/sourcemod/scripting/soap_tf2dm.sp#L866

(basically only modify their health if their current health is below their max health)

**Comment by icewind1991** [comment]
Fixed with bc3ce5ec3822b3ed90e0e2e2e53f92d2c91b2384
