### ISSUE TITLE
cp_badlands.cfg - spawns clip into world

### ISSUE THREAD

**Issue by wbv** [Lange/SOAP-TF2DM#33]
Some of the spawns for cp_badlands will put a player inside the world, unable to move.

At least the spawns underneath the small bridges, next to the spires on each side, for both teams' spawns, are affected. Unsure if more are affected.

I'd be willing to figure out corrections and submit a pull request for them if I knew how to determine coordinates in-game.

**Comment by mr64bit** [comment]
I've had problems with this on cp_steel. Seems that for some reason either an engine or MM/SM change causes 'TeleportEntity' to teleport you slightly higher or lower than intended. (depending on whether you're above or below 0 on the Z axis)
'TeleportEntity' seems to be a wrapper for a direct engine call, so I don't believe SourceMod does anything with the teleport values, just passes them to the engine.

To test to make sure this is the same issue, when you spawn in the ground, look at the values shown by 'cl_showpos 1' and see if they're the same as one of the spawn positions listed in 'configs/soap/cp_badlands.cfg'.

**Comment by Zeluboba** [comment]
Same problem.
@mr64bit yeah, for example "RED under main bridge" location is "-547.61 144.47 134.39", actually I'm at -547.61 144.47 142.39. Should we make a pull request to change the values?

**Comment by JanSGNm** [comment]
#35 resolved this issue.

**Comment by Zeluboba** [comment]
Actually that's just a tricky thing
