### ISSUE TITLE
Updater support

### ISSUE THREAD

**Issue by RisingFog** [Lange/SOAP-TF2DM#51]
I've been considering adding Updater support to SOAP, but it would require some hosting infrastructure (http only, no https). It's theoretically possible to do some free hosting with github.io so the files are auto-updated as soon as new changes are made.

The obvious benefits would be to have map configuration files always updated whenever a change is made, as well as any plugin updates.

Thoughts?

**Comment by Lange** [comment]
I'm open to this, with this following caveats:

- I'd want to retain control of the auto update server, for security reasons. If there's an easy route with github.io, this seems doable.
- It would of course need to be thoroughly tested to ensure that it works properly and won't brick people's installs if there's a bug or bad update.

I agree that having auto updating map configuration files would be great for UX.

**Comment by RisingFog** [comment]
According to this post, it can be done: https://forums.alliedmods.net/showpost.php?p=2362523&postcount=529

Assuming, of course, that github.io is no longer served up by https still.

**Comment by Lange** [comment]
It does indeed seem that github.io pages can be accessed via both `http` and `https`.

Long-term, I do sincerely worry that `http` access might go away. There's a real push among browser vendors to greatly disincentivize the use of `http`. That said, it's here and works right now, so I'd be okay with using it. We can cross that theoretical bridge if and when we get to it.

**Comment by Lange** [comment]
Closed by #52 .

**Comment by RisingFog** [comment]
The updater doesn't actually do anything until the github.io page is set up. Once it's set up it should work.

**Comment by Lange** [comment]
I set it up before merging the PR, including populating it with the files from your branch.

**Comment by RisingFog** [comment]
Oh, well the updatefile.txt needs to be added to the gh-pages branch.

**Comment by Lange** [comment]
Ahh yes, I forgot to add that. It's been committed and pushed.
